/*
 * Library Management
 * Simple REST API for Library Management System, primarily just to track books
 *
 * OpenAPI spec version: 1.0.11
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.40
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Book model module.
 * @module model/Book
 * @version 1.0.11
 */
export class Book {
  /**
   * Constructs a new <code>Book</code>.
   * @alias module:model/Book
   * @class
   * @param isbn {Number} 
   * @param name {String} 
   */
  constructor(isbn, name) {
    this.isbn = isbn;
    this.name = name;
  }

  /**
   * Constructs a <code>Book</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Book} obj Optional instance to populate.
   * @return {module:model/Book} The populated <code>Book</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Book();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('isbn'))
        obj.isbn = ApiClient.convertToType(data['isbn'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('author'))
        obj.author = ApiClient.convertToType(data['author'], 'String');
      if (data.hasOwnProperty('no of pages'))
        obj.noOfPages = ApiClient.convertToType(data['no of pages'], 'Number');
      if (data.hasOwnProperty('publication date'))
        obj.publicationDate = ApiClient.convertToType(data['publication date'], 'String');
      if (data.hasOwnProperty('genre'))
        obj.genre = ApiClient.convertToType(data['genre'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Book.prototype.id = undefined;

/**
 * @member {Number} isbn
 */
Book.prototype.isbn = undefined;

/**
 * @member {String} name
 */
Book.prototype.name = undefined;

/**
 * @member {String} author
 */
Book.prototype.author = undefined;

/**
 * @member {Number} noOfPages
 */
Book.prototype.noOfPages = undefined;

/**
 * @member {String} publicationDate
 */
Book.prototype.publicationDate = undefined;

/**
 * @member {String} genre
 */
Book.prototype.genre = undefined;

