/*
 * Library Management
 * Simple REST API for Library Management System, primarily just to track books
 *
 * OpenAPI spec version: 1.0.11
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.40
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LibraryManagement);
  }
}(this, function(expect, LibraryManagement) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LibraryManagement.BookApi();
  });

  describe('(package)', function() {
    describe('BookApi', function() {
      describe('addBook', function() {
        it('should call addBook successfully', function(done) {
          // TODO: uncomment, update parameter values for addBook call and complete the assertions
          /*

          instance.addBook(body, id, isbn, name, author, noOfPages, publicationDate, genre, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(LibraryManagement.Book);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteBook', function() {
        it('should call deleteBook successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteBook call
          /*

          instance.deleteBook(bookId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getBook', function() {
        it('should call getBook successfully', function(done) {
          // TODO: uncomment getBook call and complete the assertions
          /*

          instance.getBook(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(LibraryManagement.Book);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getBookById', function() {
        it('should call getBookById successfully', function(done) {
          // TODO: uncomment, update parameter values for getBookById call and complete the assertions
          /*

          instance.getBookById(bookId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(LibraryManagement.Book);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('replaceBook', function() {
        it('should call replaceBook successfully', function(done) {
          // TODO: uncomment, update parameter values for replaceBook call and complete the assertions
          /*

          instance.replaceBook(body, id, isbn, name, author, noOfPages, publicationDate, genre, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(LibraryManagement.Book);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('searchBook', function() {
        it('should call searchBook successfully', function(done) {
          // TODO: uncomment, update parameter values for searchBook call and complete the assertions
          /*
          var opts = {};

          instance.searchBook(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(LibraryManagement.Book);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateBookById', function() {
        it('should call updateBookById successfully', function(done) {
          // TODO: uncomment, update parameter values for updateBookById call
          /*
          var opts = {};

          instance.updateBookById(bookId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
